<?php

/**
 * BaseDetallesPagosTalentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha_pago
 * @property integer $user_id
 * @property integer $pagos_talentos_id
 * @property integer $detalles_cotizacion_id
 * @property integer $metodo_recibo
 * @property double $importe
 * @property double $iva
 * @property double $isr
 * @property double $descuento
 * @property integer $status
 * @property PagosTalentos $PagosTalentos
 * @property DetallesCotizacion $DetallesCotizacion
 * @property sfGuardUser $User
 * 
 * @method date                  getFechaPago()              Returns the current record's "fecha_pago" value
 * @method integer               getUserId()                 Returns the current record's "user_id" value
 * @method integer               getPagosTalentosId()        Returns the current record's "pagos_talentos_id" value
 * @method integer               getDetallesCotizacionId()   Returns the current record's "detalles_cotizacion_id" value
 * @method integer               getMetodoRecibo()           Returns the current record's "metodo_recibo" value
 * @method double                getImporte()                Returns the current record's "importe" value
 * @method double                getIva()                    Returns the current record's "iva" value
 * @method double                getIsr()                    Returns the current record's "isr" value
 * @method double                getDescuento()              Returns the current record's "descuento" value
 * @method integer               getStatus()                 Returns the current record's "status" value
 * @method PagosTalentos         getPagosTalentos()          Returns the current record's "PagosTalentos" value
 * @method DetallesCotizacion    getDetallesCotizacion()     Returns the current record's "DetallesCotizacion" value
 * @method sfGuardUser           getUser()                   Returns the current record's "User" value
 * @method DetallesPagosTalentos setFechaPago()              Sets the current record's "fecha_pago" value
 * @method DetallesPagosTalentos setUserId()                 Sets the current record's "user_id" value
 * @method DetallesPagosTalentos setPagosTalentosId()        Sets the current record's "pagos_talentos_id" value
 * @method DetallesPagosTalentos setDetallesCotizacionId()   Sets the current record's "detalles_cotizacion_id" value
 * @method DetallesPagosTalentos setMetodoRecibo()           Sets the current record's "metodo_recibo" value
 * @method DetallesPagosTalentos setImporte()                Sets the current record's "importe" value
 * @method DetallesPagosTalentos setIva()                    Sets the current record's "iva" value
 * @method DetallesPagosTalentos setIsr()                    Sets the current record's "isr" value
 * @method DetallesPagosTalentos setDescuento()              Sets the current record's "descuento" value
 * @method DetallesPagosTalentos setStatus()                 Sets the current record's "status" value
 * @method DetallesPagosTalentos setPagosTalentos()          Sets the current record's "PagosTalentos" value
 * @method DetallesPagosTalentos setDetallesCotizacion()     Sets the current record's "DetallesCotizacion" value
 * @method DetallesPagosTalentos setUser()                   Sets the current record's "User" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetallesPagosTalentos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalles_pagos_talentos');
        $this->hasColumn('fecha_pago', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pagos_talentos_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('detalles_cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('metodo_recibo', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('importe', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('iva', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('isr', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('descuento', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PagosTalentos', array(
             'local' => 'pagos_talentos_id',
             'foreign' => 'id'));

        $this->hasOne('DetallesCotizacion', array(
             'local' => 'detalles_cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}