<?php

/**
 * BaseDetallesCotizacionComisionistas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $detalles_cotizacion_id
 * @property integer $comisionista_id
 * @property float $margen
 * @property double $ganancia
 * @property integer $nivel
 * @property DetallesCotizacion $DetallesCotizacion
 * @property Comisionistas $Comisionistas
 * 
 * @method integer                         getDetallesCotizacionId()   Returns the current record's "detalles_cotizacion_id" value
 * @method integer                         getComisionistaId()         Returns the current record's "comisionista_id" value
 * @method float                           getMargen()                 Returns the current record's "margen" value
 * @method double                          getGanancia()               Returns the current record's "ganancia" value
 * @method integer                         getNivel()                  Returns the current record's "nivel" value
 * @method DetallesCotizacion              getDetallesCotizacion()     Returns the current record's "DetallesCotizacion" value
 * @method Comisionistas                   getComisionistas()          Returns the current record's "Comisionistas" value
 * @method DetallesCotizacionComisionistas setDetallesCotizacionId()   Sets the current record's "detalles_cotizacion_id" value
 * @method DetallesCotizacionComisionistas setComisionistaId()         Sets the current record's "comisionista_id" value
 * @method DetallesCotizacionComisionistas setMargen()                 Sets the current record's "margen" value
 * @method DetallesCotizacionComisionistas setGanancia()               Sets the current record's "ganancia" value
 * @method DetallesCotizacionComisionistas setNivel()                  Sets the current record's "nivel" value
 * @method DetallesCotizacionComisionistas setDetallesCotizacion()     Sets the current record's "DetallesCotizacion" value
 * @method DetallesCotizacionComisionistas setComisionistas()          Sets the current record's "Comisionistas" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetallesCotizacionComisionistas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalles_cotizacion_comisionistas');
        $this->hasColumn('detalles_cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comisionista_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('margen', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('ganancia', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('nivel', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             'length' => 1,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetallesCotizacion', array(
             'local' => 'detalles_cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('Comisionistas', array(
             'local' => 'comisionista_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}