<?php

/**
 * BasePagos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $referencia
 * @property integer $cliente_id
 * @property double $importe
 * @property double $iva
 * @property double $adeudo
 * @property boolean $is_cerrado
 * @property Clientes $Clientes
 * @property Doctrine_Collection $DetallesPagos
 * 
 * @method string              getReferencia()    Returns the current record's "referencia" value
 * @method integer             getClienteId()     Returns the current record's "cliente_id" value
 * @method double              getImporte()       Returns the current record's "importe" value
 * @method double              getIva()           Returns the current record's "iva" value
 * @method double              getAdeudo()        Returns the current record's "adeudo" value
 * @method boolean             getIsCerrado()     Returns the current record's "is_cerrado" value
 * @method Clientes            getClientes()      Returns the current record's "Clientes" value
 * @method Doctrine_Collection getDetallesPagos() Returns the current record's "DetallesPagos" collection
 * @method Pagos               setReferencia()    Sets the current record's "referencia" value
 * @method Pagos               setClienteId()     Sets the current record's "cliente_id" value
 * @method Pagos               setImporte()       Sets the current record's "importe" value
 * @method Pagos               setIva()           Sets the current record's "iva" value
 * @method Pagos               setAdeudo()        Sets the current record's "adeudo" value
 * @method Pagos               setIsCerrado()     Sets the current record's "is_cerrado" value
 * @method Pagos               setClientes()      Sets the current record's "Clientes" value
 * @method Pagos               setDetallesPagos() Sets the current record's "DetallesPagos" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePagos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pagos');
        $this->hasColumn('referencia', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('importe', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('iva', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('adeudo', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('is_cerrado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clientes', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasMany('DetallesPagos', array(
             'local' => 'id',
             'foreign' => 'pagos_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}