<?php

/**
 * BaseEventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $talento_id
 * @property integer $cotizacion_id
 * @property datetime $inicia_evento
 * @property datetime $termina_evento
 * @property boolean $es_dia_completo
 * @property boolean $repetir_evento
 * @property integer $tipo_repetir
 * @property date $repetir_inicia
 * @property date $repetir_termina
 * @property integer $status
 * @property boolean $is_active
 * @property Cotizaciones $Cotizaciones
 * @property Talentos $Talentos
 * 
 * @method integer      getTalentoId()       Returns the current record's "talento_id" value
 * @method integer      getCotizacionId()    Returns the current record's "cotizacion_id" value
 * @method datetime     getIniciaEvento()    Returns the current record's "inicia_evento" value
 * @method datetime     getTerminaEvento()   Returns the current record's "termina_evento" value
 * @method boolean      getEsDiaCompleto()   Returns the current record's "es_dia_completo" value
 * @method boolean      getRepetirEvento()   Returns the current record's "repetir_evento" value
 * @method integer      getTipoRepetir()     Returns the current record's "tipo_repetir" value
 * @method date         getRepetirInicia()   Returns the current record's "repetir_inicia" value
 * @method date         getRepetirTermina()  Returns the current record's "repetir_termina" value
 * @method integer      getStatus()          Returns the current record's "status" value
 * @method boolean      getIsActive()        Returns the current record's "is_active" value
 * @method Cotizaciones getCotizaciones()    Returns the current record's "Cotizaciones" value
 * @method Talentos     getTalentos()        Returns the current record's "Talentos" value
 * @method Eventos      setTalentoId()       Sets the current record's "talento_id" value
 * @method Eventos      setCotizacionId()    Sets the current record's "cotizacion_id" value
 * @method Eventos      setIniciaEvento()    Sets the current record's "inicia_evento" value
 * @method Eventos      setTerminaEvento()   Sets the current record's "termina_evento" value
 * @method Eventos      setEsDiaCompleto()   Sets the current record's "es_dia_completo" value
 * @method Eventos      setRepetirEvento()   Sets the current record's "repetir_evento" value
 * @method Eventos      setTipoRepetir()     Sets the current record's "tipo_repetir" value
 * @method Eventos      setRepetirInicia()   Sets the current record's "repetir_inicia" value
 * @method Eventos      setRepetirTermina()  Sets the current record's "repetir_termina" value
 * @method Eventos      setStatus()          Sets the current record's "status" value
 * @method Eventos      setIsActive()        Sets the current record's "is_active" value
 * @method Eventos      setCotizaciones()    Sets the current record's "Cotizaciones" value
 * @method Eventos      setTalentos()        Sets the current record's "Talentos" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eventos');
        $this->hasColumn('talento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('inicia_evento', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('termina_evento', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => false,
             ));
        $this->hasColumn('es_dia_completo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('repetir_evento', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
        $this->hasColumn('tipo_repetir', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('repetir_inicia', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('repetir_termina', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cotizaciones', array(
             'local' => 'cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('Talentos', array(
             'local' => 'talento_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}