<?php

/**
 * BaseCotizacionesConceptos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cotizacion_id
 * @property integer $concepto_id
 * @property double $precio
 * @property Cotizaciones $Cotizaciones
 * @property Conceptos $Conceptos
 * 
 * @method integer               getCotizacionId()  Returns the current record's "cotizacion_id" value
 * @method integer               getConceptoId()    Returns the current record's "concepto_id" value
 * @method double                getPrecio()        Returns the current record's "precio" value
 * @method Cotizaciones          getCotizaciones()  Returns the current record's "Cotizaciones" value
 * @method Conceptos             getConceptos()     Returns the current record's "Conceptos" value
 * @method CotizacionesConceptos setCotizacionId()  Sets the current record's "cotizacion_id" value
 * @method CotizacionesConceptos setConceptoId()    Sets the current record's "concepto_id" value
 * @method CotizacionesConceptos setPrecio()        Sets the current record's "precio" value
 * @method CotizacionesConceptos setCotizaciones()  Sets the current record's "Cotizaciones" value
 * @method CotizacionesConceptos setConceptos()     Sets the current record's "Conceptos" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizacionesConceptos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_conceptos');
        $this->hasColumn('cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('concepto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('precio', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cotizaciones', array(
             'local' => 'cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('Conceptos', array(
             'local' => 'concepto_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}