<?php

/**
 * BaseCotizacionesEventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cotizacion_id
 * @property integer $evento_id
 * @property Cotizaciones $Cotizaciones
 * @property KsWCEvent $Eventos
 * 
 * @method integer             getCotizacionId()  Returns the current record's "cotizacion_id" value
 * @method integer             getEventoId()      Returns the current record's "evento_id" value
 * @method Cotizaciones        getCotizaciones()  Returns the current record's "Cotizaciones" value
 * @method KsWCEvent           getEventos()       Returns the current record's "Eventos" value
 * @method CotizacionesEventos setCotizacionId()  Sets the current record's "cotizacion_id" value
 * @method CotizacionesEventos setEventoId()      Sets the current record's "evento_id" value
 * @method CotizacionesEventos setCotizaciones()  Sets the current record's "Cotizaciones" value
 * @method CotizacionesEventos setEventos()       Sets the current record's "Eventos" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizacionesEventos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_eventos');
        $this->hasColumn('cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('evento_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cotizaciones', array(
             'local' => 'cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('KsWCEvent as Eventos', array(
             'local' => 'evento_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}