<?php

/**
 * BaseContactos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $apellidos
 * @property string $calle
 * @property string $numero_exterior
 * @property string $numero_interior
 * @property string $colonia
 * @property string $codigo_postal
 * @property string $cuidad
 * @property string $municipio
 * @property string $estado
 * @property string $pais
 * @property string $telefono
 * @property string $celular
 * @property string $email
 * @property boolean $is_active
 * @property Doctrine_Collection $Clientes
 * @property Doctrine_Collection $ClientesContactos
 * @property Doctrine_Collection $Precotizaciones
 * @property Doctrine_Collection $Cotizaciones
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getApellidos()         Returns the current record's "apellidos" value
 * @method string              getCalle()             Returns the current record's "calle" value
 * @method string              getNumeroExterior()    Returns the current record's "numero_exterior" value
 * @method string              getNumeroInterior()    Returns the current record's "numero_interior" value
 * @method string              getColonia()           Returns the current record's "colonia" value
 * @method string              getCodigoPostal()      Returns the current record's "codigo_postal" value
 * @method string              getCuidad()            Returns the current record's "cuidad" value
 * @method string              getMunicipio()         Returns the current record's "municipio" value
 * @method string              getEstado()            Returns the current record's "estado" value
 * @method string              getPais()              Returns the current record's "pais" value
 * @method string              getTelefono()          Returns the current record's "telefono" value
 * @method string              getCelular()           Returns the current record's "celular" value
 * @method string              getEmail()             Returns the current record's "email" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getClientes()          Returns the current record's "Clientes" collection
 * @method Doctrine_Collection getClientesContactos() Returns the current record's "ClientesContactos" collection
 * @method Doctrine_Collection getPrecotizaciones()   Returns the current record's "Precotizaciones" collection
 * @method Doctrine_Collection getCotizaciones()      Returns the current record's "Cotizaciones" collection
 * @method Contactos           setName()              Sets the current record's "name" value
 * @method Contactos           setApellidos()         Sets the current record's "apellidos" value
 * @method Contactos           setCalle()             Sets the current record's "calle" value
 * @method Contactos           setNumeroExterior()    Sets the current record's "numero_exterior" value
 * @method Contactos           setNumeroInterior()    Sets the current record's "numero_interior" value
 * @method Contactos           setColonia()           Sets the current record's "colonia" value
 * @method Contactos           setCodigoPostal()      Sets the current record's "codigo_postal" value
 * @method Contactos           setCuidad()            Sets the current record's "cuidad" value
 * @method Contactos           setMunicipio()         Sets the current record's "municipio" value
 * @method Contactos           setEstado()            Sets the current record's "estado" value
 * @method Contactos           setPais()              Sets the current record's "pais" value
 * @method Contactos           setTelefono()          Sets the current record's "telefono" value
 * @method Contactos           setCelular()           Sets the current record's "celular" value
 * @method Contactos           setEmail()             Sets the current record's "email" value
 * @method Contactos           setIsActive()          Sets the current record's "is_active" value
 * @method Contactos           setClientes()          Sets the current record's "Clientes" collection
 * @method Contactos           setClientesContactos() Sets the current record's "ClientesContactos" collection
 * @method Contactos           setPrecotizaciones()   Sets the current record's "Precotizaciones" collection
 * @method Contactos           setCotizaciones()      Sets the current record's "Cotizaciones" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContactos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contactos');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellidos', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('calle', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('numero_exterior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('numero_interior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('colonia', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('codigo_postal', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('cuidad', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('municipio', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('estado', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('pais', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('telefono', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('celular', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Clientes', array(
             'refClass' => 'ClientesContactos',
             'local' => 'cliente_id',
             'foreign' => 'contacto_id'));

        $this->hasMany('ClientesContactos', array(
             'local' => 'id',
             'foreign' => 'contacto_id'));

        $this->hasMany('Precotizaciones', array(
             'local' => 'id',
             'foreign' => 'contacto_id'));

        $this->hasMany('Cotizaciones', array(
             'local' => 'id',
             'foreign' => 'contacto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'apellidos',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}