<?php

/**
 * BaseDetallesPagos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha_pago
 * @property integer $user_id
 * @property integer $pagos_id
 * @property integer $cotizacion_id
 * @property integer $tipo_pago
 * @property double $importe
 * @property double $iva
 * @property integer $status
 * @property Pagos $Pagos
 * @property Cotizaciones $Cotizaciones
 * @property sfGuardUser $User
 * 
 * @method date          getFechaPago()     Returns the current record's "fecha_pago" value
 * @method integer       getUserId()        Returns the current record's "user_id" value
 * @method integer       getPagosId()       Returns the current record's "pagos_id" value
 * @method integer       getCotizacionId()  Returns the current record's "cotizacion_id" value
 * @method integer       getTipoPago()      Returns the current record's "tipo_pago" value
 * @method double        getImporte()       Returns the current record's "importe" value
 * @method double        getIva()           Returns the current record's "iva" value
 * @method integer       getStatus()        Returns the current record's "status" value
 * @method Pagos         getPagos()         Returns the current record's "Pagos" value
 * @method Cotizaciones  getCotizaciones()  Returns the current record's "Cotizaciones" value
 * @method sfGuardUser   getUser()          Returns the current record's "User" value
 * @method DetallesPagos setFechaPago()     Sets the current record's "fecha_pago" value
 * @method DetallesPagos setUserId()        Sets the current record's "user_id" value
 * @method DetallesPagos setPagosId()       Sets the current record's "pagos_id" value
 * @method DetallesPagos setCotizacionId()  Sets the current record's "cotizacion_id" value
 * @method DetallesPagos setTipoPago()      Sets the current record's "tipo_pago" value
 * @method DetallesPagos setImporte()       Sets the current record's "importe" value
 * @method DetallesPagos setIva()           Sets the current record's "iva" value
 * @method DetallesPagos setStatus()        Sets the current record's "status" value
 * @method DetallesPagos setPagos()         Sets the current record's "Pagos" value
 * @method DetallesPagos setCotizaciones()  Sets the current record's "Cotizaciones" value
 * @method DetallesPagos setUser()          Sets the current record's "User" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetallesPagos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalles_pagos');
        $this->hasColumn('fecha_pago', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pagos_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo_pago', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('importe', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('iva', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pagos', array(
             'local' => 'pagos_id',
             'foreign' => 'id'));

        $this->hasOne('Cotizaciones', array(
             'local' => 'cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}