<?php

/**
 * BasePrecotizaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cliente_id
 * @property integer $contacto_id
 * @property integer $user_id
 * @property string $evento
 * @property text $descripcion
 * @property text $actividad_general
 * @property string $lugar_evento
 * @property datetime $inicia_evento
 * @property datetime $termina_evento
 * @property string $pdf
 * @property integer $status
 * @property boolean $is_active
 * @property Clientes $Clientes
 * @property Contactos $Contactos
 * @property sfGuardUser $User
 * @property Doctrine_Collection $DetallesPrecotizacion
 * 
 * @method integer             getClienteId()             Returns the current record's "cliente_id" value
 * @method integer             getContactoId()            Returns the current record's "contacto_id" value
 * @method integer             getUserId()                Returns the current record's "user_id" value
 * @method string              getEvento()                Returns the current record's "evento" value
 * @method text                getDescripcion()           Returns the current record's "descripcion" value
 * @method text                getActividadGeneral()      Returns the current record's "actividad_general" value
 * @method string              getLugarEvento()           Returns the current record's "lugar_evento" value
 * @method datetime            getIniciaEvento()          Returns the current record's "inicia_evento" value
 * @method datetime            getTerminaEvento()         Returns the current record's "termina_evento" value
 * @method string              getPdf()                   Returns the current record's "pdf" value
 * @method integer             getStatus()                Returns the current record's "status" value
 * @method boolean             getIsActive()              Returns the current record's "is_active" value
 * @method Clientes            getClientes()              Returns the current record's "Clientes" value
 * @method Contactos           getContactos()             Returns the current record's "Contactos" value
 * @method sfGuardUser         getUser()                  Returns the current record's "User" value
 * @method Doctrine_Collection getDetallesPrecotizacion() Returns the current record's "DetallesPrecotizacion" collection
 * @method Precotizaciones     setClienteId()             Sets the current record's "cliente_id" value
 * @method Precotizaciones     setContactoId()            Sets the current record's "contacto_id" value
 * @method Precotizaciones     setUserId()                Sets the current record's "user_id" value
 * @method Precotizaciones     setEvento()                Sets the current record's "evento" value
 * @method Precotizaciones     setDescripcion()           Sets the current record's "descripcion" value
 * @method Precotizaciones     setActividadGeneral()      Sets the current record's "actividad_general" value
 * @method Precotizaciones     setLugarEvento()           Sets the current record's "lugar_evento" value
 * @method Precotizaciones     setIniciaEvento()          Sets the current record's "inicia_evento" value
 * @method Precotizaciones     setTerminaEvento()         Sets the current record's "termina_evento" value
 * @method Precotizaciones     setPdf()                   Sets the current record's "pdf" value
 * @method Precotizaciones     setStatus()                Sets the current record's "status" value
 * @method Precotizaciones     setIsActive()              Sets the current record's "is_active" value
 * @method Precotizaciones     setClientes()              Sets the current record's "Clientes" value
 * @method Precotizaciones     setContactos()             Sets the current record's "Contactos" value
 * @method Precotizaciones     setUser()                  Sets the current record's "User" value
 * @method Precotizaciones     setDetallesPrecotizacion() Sets the current record's "DetallesPrecotizacion" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrecotizaciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('precotizaciones');
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('contacto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('evento', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('actividad_general', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('lugar_evento', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('inicia_evento', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('termina_evento', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('pdf', 'string', 255, array(
             'type' => 'string',
             'default' => 'sin_archivo.pdf',
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clientes', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasOne('Contactos', array(
             'local' => 'contacto_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('DetallesPrecotizacion', array(
             'local' => 'id',
             'foreign' => 'precotizacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'evento',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
        $this->actAs($sluggable0);
    }
}