<?php

/**
 * BaseEmpresas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $empresa
 * @property date $inactivar
 * @property Doctrine_Collection $Precotizaciones
 * @property Doctrine_Collection $Cotizaciones
 * 
 * @method string              getEmpresa()         Returns the current record's "empresa" value
 * @method date                getInactivar()       Returns the current record's "inactivar" value
 * @method Doctrine_Collection getPrecotizaciones() Returns the current record's "Precotizaciones" collection
 * @method Doctrine_Collection getCotizaciones()    Returns the current record's "Cotizaciones" collection
 * @method Empresas            setEmpresa()         Sets the current record's "empresa" value
 * @method Empresas            setInactivar()       Sets the current record's "inactivar" value
 * @method Empresas            setPrecotizaciones() Sets the current record's "Precotizaciones" collection
 * @method Empresas            setCotizaciones()    Sets the current record's "Cotizaciones" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpresas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresas');
        $this->hasColumn('empresa', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('inactivar', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Precotizaciones', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Cotizaciones', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}