<?php

/**
 * BaseRepresentantes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $apellidos
 * @property text $direccion
 * @property string $telefono
 * @property string $celular
 * @property string $email
 * @property boolean $is_active
 * @property Doctrine_Collection $Talentos
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getApellidos() Returns the current record's "apellidos" value
 * @method text                getDireccion() Returns the current record's "direccion" value
 * @method string              getTelefono()  Returns the current record's "telefono" value
 * @method string              getCelular()   Returns the current record's "celular" value
 * @method string              getEmail()     Returns the current record's "email" value
 * @method boolean             getIsActive()  Returns the current record's "is_active" value
 * @method Doctrine_Collection getTalentos()  Returns the current record's "Talentos" collection
 * @method Representantes      setName()      Sets the current record's "name" value
 * @method Representantes      setApellidos() Sets the current record's "apellidos" value
 * @method Representantes      setDireccion() Sets the current record's "direccion" value
 * @method Representantes      setTelefono()  Sets the current record's "telefono" value
 * @method Representantes      setCelular()   Sets the current record's "celular" value
 * @method Representantes      setEmail()     Sets the current record's "email" value
 * @method Representantes      setIsActive()  Sets the current record's "is_active" value
 * @method Representantes      setTalentos()  Sets the current record's "Talentos" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRepresentantes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('representantes');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellidos', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('direccion', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('telefono', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('celular', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('email', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Talentos', array(
             'local' => 'id',
             'foreign' => 'representante_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'apellidos',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}