<?php

/**
 * BaseComisionistas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property float $margen
 * @property Doctrine_Collection $CotizacionesComisionistas
 * @property Doctrine_Collection $DetallesCotizacionComisionistas
 * 
 * @method string              getNombre()                          Returns the current record's "nombre" value
 * @method float               getMargen()                          Returns the current record's "margen" value
 * @method Doctrine_Collection getCotizacionesComisionistas()       Returns the current record's "CotizacionesComisionistas" collection
 * @method Doctrine_Collection getDetallesCotizacionComisionistas() Returns the current record's "DetallesCotizacionComisionistas" collection
 * @method Comisionistas       setNombre()                          Sets the current record's "nombre" value
 * @method Comisionistas       setMargen()                          Sets the current record's "margen" value
 * @method Comisionistas       setCotizacionesComisionistas()       Sets the current record's "CotizacionesComisionistas" collection
 * @method Comisionistas       setDetallesCotizacionComisionistas() Sets the current record's "DetallesCotizacionComisionistas" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComisionistas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comisionistas');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('margen', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CotizacionesComisionistas', array(
             'local' => 'id',
             'foreign' => 'comisionista_id'));

        $this->hasMany('DetallesCotizacionComisionistas', array(
             'local' => 'id',
             'foreign' => 'comisionista_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}