<?php

/**
 * BaseClientes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $razon_social
 * @property string $rfc
 * @property string $calle
 * @property string $numero_exterior
 * @property string $numero_interior
 * @property string $colonia
 * @property string $codigo_postal
 * @property string $cuidad
 * @property string $municipio
 * @property string $estado
 * @property string $pais
 * @property double $saldo
 * @property boolean $is_active
 * @property Doctrine_Collection $Contactos
 * @property Doctrine_Collection $ClientesContactos
 * @property Doctrine_Collection $Precotizaciones
 * @property Doctrine_Collection $Cotizaciones
 * @property Doctrine_Collection $Pagos
 * 
 * @method string              getRazonSocial()       Returns the current record's "razon_social" value
 * @method string              getRfc()               Returns the current record's "rfc" value
 * @method string              getCalle()             Returns the current record's "calle" value
 * @method string              getNumeroExterior()    Returns the current record's "numero_exterior" value
 * @method string              getNumeroInterior()    Returns the current record's "numero_interior" value
 * @method string              getColonia()           Returns the current record's "colonia" value
 * @method string              getCodigoPostal()      Returns the current record's "codigo_postal" value
 * @method string              getCuidad()            Returns the current record's "cuidad" value
 * @method string              getMunicipio()         Returns the current record's "municipio" value
 * @method string              getEstado()            Returns the current record's "estado" value
 * @method string              getPais()              Returns the current record's "pais" value
 * @method double              getSaldo()             Returns the current record's "saldo" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method Doctrine_Collection getContactos()         Returns the current record's "Contactos" collection
 * @method Doctrine_Collection getClientesContactos() Returns the current record's "ClientesContactos" collection
 * @method Doctrine_Collection getPrecotizaciones()   Returns the current record's "Precotizaciones" collection
 * @method Doctrine_Collection getCotizaciones()      Returns the current record's "Cotizaciones" collection
 * @method Doctrine_Collection getPagos()             Returns the current record's "Pagos" collection
 * @method Clientes            setRazonSocial()       Sets the current record's "razon_social" value
 * @method Clientes            setRfc()               Sets the current record's "rfc" value
 * @method Clientes            setCalle()             Sets the current record's "calle" value
 * @method Clientes            setNumeroExterior()    Sets the current record's "numero_exterior" value
 * @method Clientes            setNumeroInterior()    Sets the current record's "numero_interior" value
 * @method Clientes            setColonia()           Sets the current record's "colonia" value
 * @method Clientes            setCodigoPostal()      Sets the current record's "codigo_postal" value
 * @method Clientes            setCuidad()            Sets the current record's "cuidad" value
 * @method Clientes            setMunicipio()         Sets the current record's "municipio" value
 * @method Clientes            setEstado()            Sets the current record's "estado" value
 * @method Clientes            setPais()              Sets the current record's "pais" value
 * @method Clientes            setSaldo()             Sets the current record's "saldo" value
 * @method Clientes            setIsActive()          Sets the current record's "is_active" value
 * @method Clientes            setContactos()         Sets the current record's "Contactos" collection
 * @method Clientes            setClientesContactos() Sets the current record's "ClientesContactos" collection
 * @method Clientes            setPrecotizaciones()   Sets the current record's "Precotizaciones" collection
 * @method Clientes            setCotizaciones()      Sets the current record's "Cotizaciones" collection
 * @method Clientes            setPagos()             Sets the current record's "Pagos" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clientes');
        $this->hasColumn('razon_social', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('rfc', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('calle', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('numero_exterior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('numero_interior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('colonia', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('codigo_postal', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('cuidad', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('municipio', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('estado', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('pais', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('saldo', 'double', null, array(
             'type' => 'double',
             'notnull' => false,
             'default' => 0,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contactos', array(
             'refClass' => 'ClientesContactos',
             'local' => 'contacto_id',
             'foreign' => 'cliente_id'));

        $this->hasMany('ClientesContactos', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Precotizaciones', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Cotizaciones', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $this->hasMany('Pagos', array(
             'local' => 'id',
             'foreign' => 'cliente_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'razon_social',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}