<?php

/**
 * BaseDetallesCotizacionEventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $detalle_cotizacion_id
 * @property integer $evento_id
 * @property DetallesCotizacion $DetallesCotizacion
 * @property KsWCEvent $Eventos
 * 
 * @method integer                   getDetalleCotizacionId()   Returns the current record's "detalle_cotizacion_id" value
 * @method integer                   getEventoId()              Returns the current record's "evento_id" value
 * @method DetallesCotizacion        getDetallesCotizacion()    Returns the current record's "DetallesCotizacion" value
 * @method KsWCEvent                 getEventos()               Returns the current record's "Eventos" value
 * @method DetallesCotizacionEventos setDetalleCotizacionId()   Sets the current record's "detalle_cotizacion_id" value
 * @method DetallesCotizacionEventos setEventoId()              Sets the current record's "evento_id" value
 * @method DetallesCotizacionEventos setDetallesCotizacion()    Sets the current record's "DetallesCotizacion" value
 * @method DetallesCotizacionEventos setEventos()               Sets the current record's "Eventos" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetallesCotizacionEventos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalles_cotizacion_eventos');
        $this->hasColumn('detalle_cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('evento_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetallesCotizacion', array(
             'local' => 'detalle_cotizacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('KsWCEvent as Eventos', array(
             'local' => 'evento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}