<?php

/**
 * BaseCotizacionesComisionistas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cotizacion_id
 * @property integer $comisionista_id
 * @property float $margen
 * @property Cotizaciones $Cotizaciones
 * @property Comisionistas $Comisionistas
 * 
 * @method integer                   getCotizacionId()    Returns the current record's "cotizacion_id" value
 * @method integer                   getComisionistaId()  Returns the current record's "comisionista_id" value
 * @method float                     getMargen()          Returns the current record's "margen" value
 * @method Cotizaciones              getCotizaciones()    Returns the current record's "Cotizaciones" value
 * @method Comisionistas             getComisionistas()   Returns the current record's "Comisionistas" value
 * @method CotizacionesComisionistas setCotizacionId()    Sets the current record's "cotizacion_id" value
 * @method CotizacionesComisionistas setComisionistaId()  Sets the current record's "comisionista_id" value
 * @method CotizacionesComisionistas setMargen()          Sets the current record's "margen" value
 * @method CotizacionesComisionistas setCotizaciones()    Sets the current record's "Cotizaciones" value
 * @method CotizacionesComisionistas setComisionistas()   Sets the current record's "Comisionistas" value
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCotizacionesComisionistas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cotizaciones_comisionistas');
        $this->hasColumn('cotizacion_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('comisionista_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('margen', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             'default' => 0,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cotizaciones', array(
             'local' => 'cotizacion_id',
             'foreign' => 'id'));

        $this->hasOne('Comisionistas', array(
             'local' => 'comisionista_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}