<?php

/**
 * ClientesContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientesContactosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientesContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientesContactos');
    }
}