<?php

/**
 * ClientesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clientes');
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('Clientes c')
           ->orderBy('c.razon_social asc');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('Clientes c')
                ->orderBy('c.updated_at DESC');
        return $q;
    }
    public function getCriteriaUltimosClientes(){
        $q=$this->getCriteriaOrdenadaPorActualizacion();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Contactos o');
        return $q;
    }
    public function getMaximo(){
        $q=$this->getCriteriaOrdenada();
        $cmd=$q->execute();
        return $cmd->count()+1;
    }
    public function getClientesShow($id)
    {
        $q=$this->getCriteriaOrdenada();   
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Contactos contacto');
        $q->leftJoin($rootAlias . '.Pagos p');
        $q->leftJoin($rootAlias . '.Cotizaciones cot');
        $q->leftJoin('cot.Clientes cli');
        $q->leftJoin('cot.Contactos cotcontacto');
        $q->addWhere($rootAlias.'.id=?',$id);
        if(sfContext::getInstance()->getUser()->getModoCotizacion()){
            $q->addWhere($rootAlias.'.is_active=?',true);
        }
        return $q->fetchOne();
    }
    
    public function retrieveBackendClientesList(Doctrine_Query $q)
    {
        //$q=$this->getCriteriaOrdenada();   
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Contactos contacto');
        $q->leftJoin($rootAlias . '.Pagos p');
        $q->leftJoin($rootAlias . '.Cotizaciones cot');
        if(sfContext::getInstance()->getUser()->getModoCotizacion()){
            $q->addWhere($rootAlias.'.is_active=?',true);
        }
        return $q;
    }
    
    public function getHistorialPagosClientes(array $valores){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $desde=$valores['desde']['year']."-".$valores['desde']['month']."-".$valores['desde']['day'];
        $hasta=$valores['hasta']['year']."-".$valores['hasta']['month']."-".$valores['hasta']['day'];
        $q->leftJoin($rootAlias . '.Pagos p');
        $q->leftJoin('p.DetallesPagos dp');
        $q->addWhere('dp.fecha_pago BETWEEN ? to ?',array($desde,$hasta));
        $q->addWhere('dp.status=?',$valores['status']);
        $q->addOrderBy('dp.cotizacion_id asc');
        $q->addOrderBy('dp.fecha_pago asc');
        
        if($valores['cliente']>0){
            $q->addWhere($rootAlias . '.id=?',$valores['cliente']);
        }
        
        if($valores['contacto']>0){
            $q->leftJoin($rootAlias . '.Contactos contacto');
            $q->addWhere('contacto.id=?',$valores['contacto']);
        }
        
        return $q->execute();
    }
    
}