<?php

/**
 * ComisionistasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComisionistasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComisionistasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comisionistas');
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('Comisionistas comi')
           ->orderBy('comi.nombre asc');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('Comisionistas comi')
                ->orderBy('comi.updated_at DESC');
        return $q;
    }
    public function getCriteriaFiltrarPorDetalleCotizacion($id){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->addWhere($rootAlias .'.id NOT IN (
            SELECT dcco.comisionista_id 
            FROM DetallesCotizacionComisionistas dcco
            WHERE dcco.detalles_cotizacion_id=?)', $id);     
        return $q;
    }
    
    public function getCriteriaFiltrarPorCotizacion($id){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->addWhere($rootAlias .'.id NOT IN (
            SELECT cotco.comisionista_id 
            FROM CotizacionesComisionistas cotco
            WHERE cotco.cotizacion_id=?)', $id);     
        return $q;
    }
    
    public function getCountFiltrarPorDetalleCotizacion($id){
        $q=$this->getCriteriaFiltrarPorDetalleCotizacion($id);
        return $registros=$q->count();
    }
    
    public function getCountFiltrarPorCotizacion($id){
        $q=$this->getCriteriaFiltrarPorCotizacion($id);
        return $registros=$q->count();
    }
}