<?php

/**
 * ConceptosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConceptosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConceptosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conceptos');
    }
}