<?php

/**
 * ContactosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contactos');
    }
}