<?php

/**
 * CotizacionesEventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionesEventosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionesEventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionesEventos');
    }
    public function getCriteria(){
    	$q=Doctrine_Query::create()
    	->from('CotizacionesEventos ce');
    	return $q;
    }
    
    public function getCotizacionesEventosPorCotizacionYTalento($cotizacion,$talento){
    	$q=$this->getCriteria();
    	$rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones cot');
        $q->leftJoin($rootAlias . '.Eventos e');
        $q->leftJoin('e.Talentos tal');
    	$q->where('cot.id=?',$cotizacion);
        $q->andWhere('tal.id=?',$talento);
    	return $q->execute();
    }
    public function getCotizacionesEventosPorArreglo($arreglo){
    	$q=$this->getCriteriaOrdenada();
    	$q->andWhereIn('e.id', $arreglo);
    	$rootAlias = $q->getRootAlias();
    	$q->leftJoin($rootAlias . '.Talentos t');
    	return $q->execute();
    }
}