<?php

/**
 * CotizacionesConceptosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionesConceptosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionesConceptosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionesConceptos');
    }
}