<?php

/**
 * CotizacionesComisionistasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CotizacionesComisionistasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CotizacionesComisionistasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CotizacionesComisionistas');
    }
}