<?php

/**
 * CotizacionesComisionistas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CotizacionesComisionistas extends BaseCotizacionesComisionistas
{
	public function save(\Doctrine_Connection $conn = null) {
        parent::save($conn);
        //$this->actualizarCambios();
    }
    
    public function delete(\Doctrine_Connection $conn = null) {
        $resp=$this->eliminarRegistros();
        parent::delete($conn);
        return $resp;
    }
    
    public function deleteOnly(){
        parent::delete();
    }
    public function actualizarCambios(){
        $cotizaciones=$this->getCotizaciones();
        foreach($cotizaciones->getDetallesCotizacion() as $dc){
            $existeComisionista=false;
            foreach($dc->getDetallesCotizacionComisionistas() as $dcco){
                if($dcco->getComisionistaId()==$this->getComisionistaId()){
                    $existeComisionista=true;
                    $dcco1=$dcco;
                    break;
                }
            }
            if(!$existeComisionista){
                $dcco1=new DetallesCotizacionComisionistas();
                //$dcco1->setCotizacionId($cotizaciones->getId());
                $dcco1->setDetallesCotizacionId($dc->getId());
                $dcco1->setComisionistaId($this->getComisionistaId());
                $dcco1->setMargen($this->getMargen());
                $dcco1->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
                $dcco1->setGanancia($dc->getGananciaTalento()*($this->getMargen()/100));
                $dcco1->save();
                if($this->getMargen()>0){
                    $dc->setMargenComisionistas($dc->getMargenComisionistas()+$this->getMargen());
                    $dc->calcularComisionistas();
                    $dc->getCotizaciones()->calcular();
                }
            }elseif($dcco1->getMargen()<>$this->getMargen()){
                $margenAnterior=$dcco1->getMargen();
                $dcco1->setMargen($this->getMargen());
                $dcco1->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
                $dcco1->setGanancia($dc->getGananciaTalento()*($this->getMargen()/100));
                $dcco1->save();
                $dc->setMargenComisionistas(($dc->getMargenComisionistas()-$margenAnterior)+$this->getMargen());
                $dc->calcularComisionistas();
                $dc->getCotizaciones()->calcular();
            }elseif($dcco1->getNivel()<>CotizacionesTable::$NIVEL_COTIZACION){
                $dcco1->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
                $dcco1->save();
            }
        }
    }
    
    public function eliminarRegistros(){
        $cotizaciones=$this->getCotizaciones();
        foreach($cotizaciones->getDetallesCotizacion() as $dc){
            foreach($dc->getDetallesCotizacionComisionistas() as $dcco){
                if($dcco->getComisionistaId()==$this->getComisionistaId()){
                    $dcco->delete();
                }
            }
            $dc->calcularComisionistas();
       }
        return true;
    }

}