<?php

/**
 * DetallesPagosTalentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetallesPagosTalentos extends BaseDetallesPagosTalentos
{
    public function getMetodoReciboString() {
        $choices=Doctrine_Core::getTable('DetallesPagosTalentos')->getTypes();
        return $choices[$this->getMetodoRecibo()];
    }
    public function getStatusString() {
        $choices=Doctrine_Core::getTable('DetallesPagosTalentos')->getTypesStatus();
        return $choices[$this->getStatus()];
    }
    public function save(\Doctrine_Connection $conn = null) {
        if($this->getImporte()>0){
            switch($this->getMetodoRecibo()){
                case 0: //sin dato
                    $this->setIva(0);
                    $this->setIsr(0);
                    break;
                case 1: //factura
                    $this->setIva($this->getImporte() * CotizacionesTable::$IVA);
                    $this->setIsr(0);    
                    break;
                case 2: //recibo
                    if($this->getIsr()==0)
                        $this->setIsr($this->getImporte() * CotizacionesTable::$IVA);
                    break;
            }
          
        }
        
        if(!$this->isNew()){
            if(!$this->getFechaPago()){
                $this->setFechaPago(date("Y-m-d"));
            }
            
            if(!$this->getUserId()){
                $this->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
            }
        }
                
                
        parent::save($conn);
        
        $this->getPagosTalentos()->calcular();
        
    }
    public function EsValido(){
        $resp=false;
        switch($this->getMetodoRecibo()){
                case 0: //sin dato
                    if($this->getIva()==0 && $this->getIsr()==0){
                        $resp=true;
                    }
                    break;
                case 1: //factura
                    if($this->getIva()==($this->getImporte() * CotizacionesTable::$IVA)){
                        $resp=true;
                    }    
                    break;
                case 2: //recibo
                    if($this->getIsr()>0){
                        $resp=true;
                    }
                    break;
        }
        return $resp;
    }
    
    public function liberarPago(){
        if($this->getStatus()==PagosTalentosTable::$APROBADO){
            $pago=$this->getPagosTalentos();
            $talento=$pago->getTalentos();
            $importe=$this->getImporte();
            $talento->setSaldo($talento->getSaldo()-$importe);
            $pago->setImporte($pago->getImporte()+$importe);
            $pago->setIva($pago->getIva()+$this->getIva());
            $pago->setIsr($pago->getIsr()+$this->getIsr());
            $talento->save();
            $pago->save();
            //$pago->calcular();
            $this->setStatus(PagosTalentosTable::$PAGOS_CALCULADOS);
            $this->save();
        }
    }
    
}
