<?php

/**
 * DetallesPagosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallesPagosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallesPagosTable
     */
    static public $types = array(
        '0'=> 'Sin especificar',
        '1' => 'Anticipo',
        '2' => 'Completar',
    );

    public function getTypes()
    {
      return self::$types;
    }
    
    static public $status = array(
        '0'=> 'En captura',
        '1' => 'Aprobada',
        '2' => 'Pagado',
    );

    public function getTypesStatus()
    {
      return self::$status;
    }
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallesPagos');
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('DetallesPagos dp')
           ->orderBy('dp.created_at asc');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('DetallesPagos dp')
                ->orderBy('dp.updated_at DESC');
        return $q;
    }
    public function getCriteriaUltimosRegistros(){
        $q=$this->getCriteriaOrdenadaPorActualizacion();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        return $q;
    }
    
    public function getDetallesPagosPorCotizacion($cotizacion){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        $q->addWhere($rootAlias .'.cotizacion_id=?',$cotizacion);
        return $q->execute();
    }
    
    public function getDetallesCotizacionPorFecha($fecha_inicial,$fecha_final){
        $q=$this->getCriteriaOrdenada();
        $q->addWhere('dp.updated_at BETWEEN ? to ?',array($fecha_inicial,$fecha_final));
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        $q->addOrderBy('z.created_at asc');
        return $q->execute();
    }
    
    public function getDetallesPagosPorId($pago){
        $q=$this->getCriteriaOrdenada();
        $q->addWhere('dp.pagos_id=?',$pago);
        return $q->execute();
    }
    public function addCriteriaPublicacionesActivas($q){
        $q->addWhere('dp.is_active=?',true);
        return $q;
    }
    public function getMaximo(){
        $q=$this->getCriteriaOrdenada();
        $cmd=$q->execute();
        return $cmd->count()+1;
    }
    public function retrieveBackendDetallesPagosList(Doctrine_Query $q)
    {
        $q=$this->getCriteriaOrdenada();   
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        return $q;
    }
    
        
    public function getSqlQuery($query){
        $q = Doctrine_Query::create()
             ->from('Backstage i')   
             ->where('i.contenido like ?', $query)
             ->orWhere('i.titulo like ?',$query)
             ->limit(20);
        $q = Doctrine_Core::getTable('Backstage')->addCriteriaPublicacionesActivas($q);

        return $q->execute();
    }
}