<?php

/**
 * DetallesCotizacionComisionistasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallesCotizacionComisionistasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallesCotizacionComisionistasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallesCotizacionComisionistas');
    }
}