<?php

/**
 * DetallesCotizacionConceptos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetallesCotizacionConceptos extends BaseDetallesCotizacionConceptos
{
    public function save(\Doctrine_Connection $conn = null) {
        parent::save($conn);
        $dc=$this->getDetallesCotizacion();
        $dc->calcularConceptos();
    }
    public function delete(\Doctrine_Connection $conn = null) {
        parent::delete($conn);
        return true;
    }
    
}
