<?php

/**
 * DetallesPrecotizacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallesPrecotizacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallesCotizacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallesPrecotizacion');
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('DetallesPrecotizacion dp')
           ->orderBy('dp.position asc');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('DetallesPrecotizacion dp')
                ->orderBy('dp.updated_at DESC');
        return $q;
    }
    public function getCriteriaUltimosRegistros(){
        $q=$this->getCriteriaOrdenadaPorActualizacion();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Talentos t');
        return $q;
    }
    public function getDetallesPrecotizacionConTalentos($precotizacion){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->addWhere($rootAlias . '.precotizacion_id=?',$precotizacion);
        $q->leftJoin($rootAlias . '.Talentos t');
        return $q->execute();
    }
    
    public function getDetallesPrecotizacionPorFecha($fecha_inicial,$fecha_final){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->addWhere($rootAlias.'.updated_at BETWEEN ? to ?',array($fecha_inicial,$fecha_final));
        $q->leftJoin($rootAlias . '.Talentos t');
        $q->addOrderBy($rootAlias . '.position asc');
        return $q->execute();
    }
    
    public function getDetallesPrecotizacionPorPrecotizacion($precotizacion){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Talentos t');
        $q->addWhere($rootAlias.'.precotizacion_id=?',$precotizacion);
        return $q->execute();
    }
    public function addCriteriaPublicacionesActivas($q){
        $q->addWhere('i.is_active=?',true);
        return $q;
    }
    public function getMaximo(){
        $q=$this->getCriteriaOrdenada();
        $cmd=$q->execute();
        return $cmd->count()+1;
    }
    public function retrieveBackendDetallesPrecotizacionList(Doctrine_Query $q)
    {
        $q=$this->getCriteriaOrdenada();   
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Talentos t');
        return $q;
    }
    
    public function getSqlQuery($query){
        $q = Doctrine_Query::create()
             ->from('DetallesPrecotizacion i')   
             //->where('i.titulo like ?', $query)
             ->orWhere('i.titulo like ?',$query)
             ->limit(20);
        $q = Doctrine_Core::getTable('DetallesPrecotizacion')->addCriteriaPublicacionesActivas($q);

        return $q->execute();
    }
}