<?php

/**
 * DetallesPagosTalentosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallesPagosTalentosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallesPagosTalentosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallesPagosTalentos');
    }
    static public $types = array(
        '0'=> 'Sin Impuesto',
        '1' => 'Factura (IVA)',
        '2' => 'Recibo (ISR)',
    );

    public function getTypes()
    {
      return self::$types;
    }
    
    static public $status = array(
        '0'=>  'En captura',
        '1' => 'Aprobado',
        '2' => 'Pagado',
    );

    public function getTypesStatus()
    {
      return self::$status;
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('DetallesPagosTalentos dpt')
           ->orderBy('dpt.created_at asc');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('DetallesPagosTalentos dpt')
                ->orderBy('dpt.updated_at DESC');
        return $q;
    }
    public function getCriteriaUltimosRegistros(){
        $q=$this->getCriteriaOrdenadaPorActualizacion();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        return $q;
    }
    
    public function getDetallesPagosPorCotizacion($cotizacion){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        $q->addWhere($rootAlias .'.cotizacion_id=?',$cotizacion);
        return $q->execute();
    }
    
    public function getDetallesPagosTalentosPorFecha($fecha_inicial,$fecha_final){
        $q=$this->getCriteriaOrdenada();
        $q->addWhere('dpt.updated_at BETWEEN ? to ?',array($fecha_inicial,$fecha_final));
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        $q->addOrderBy('z.created_at asc');
        return $q->execute();
    }
    
    public function getDetallesPagosTalentosPorId($pago){
        $q=$this->getCriteriaOrdenada();
        $q->addWhere('dpt.pagos_talentos_id=?',$pago);
        return $q->execute();
    }
    public function addCriteriaPublicacionesActivas($q){
        $q->addWhere('dpt.is_active=?',true);
        return $q;
    }
    public function getMaximo(){
        $q=$this->getCriteriaOrdenada();
        $cmd=$q->execute();
        return $cmd->count()+1;
    }
    public function retrieveBackendDetallesPagosTalentosList(Doctrine_Query $q)
    {
        $q=$this->getCriteriaOrdenada();   
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Cotizaciones z');
        return $q;
    }
    
        
    
    
}