<?php

/**
 * DetallesPrecotizacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetallesPrecotizacion extends BaseDetallesPrecotizacion
{
    public function save(\Doctrine_Connection $conn = null) {
        
        if(!$this->getPosition()){
            $this->setPosition(Doctrine_Core::getTable('DetallesPrecotizacion')->getMaximo());
        }
        
        
        parent::save($conn);
        
        $precotizacion=$this->getPrecotizaciones();
        $precotizacion->calcular();
    }
    
    public function delete(\Doctrine_Connection $conn = null) {
        
        $precotizacion=$this->getPrecotizaciones();
        parent::delete($conn);
        $precotizacion->calcular();
        return true;
    }
}
