<?php

/**
 * DetallesCotizacionEventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallesCotizacionEventosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallesCotizacionEventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallesCotizacionEventos');
    }
}