<?php

/**
 * DetallesCotizacionComisionistas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DetallesCotizacionComisionistas extends BaseDetallesCotizacionComisionistas
{
    public function save(\Doctrine_Connection $conn = null) {
        if(!$this->getMargen()){
            $comisionista=ComisionistasTable::getInstance()->find($this->getComisionistaId());
            $this->setMargen($comisionista->getMargen());
        }
        
        parent::save($conn);
        //$dc=$this->getDetallesCotizacion();
        //$dc->calcularComisionistas();
    }
    
    public function delete(\Doctrine_Connection $conn = null) {
        parent::delete($conn);
        return true;
    }

    public function saveOnly(\Doctrine_Connection $conn = null){
    	parent::save($conn);
    }
    
    public function getNivelString(){
        $resp="";
        switch($this->getNivel()){
            case CotizacionesTable::$NIVEL_DETALLE:
               $resp="Detalle";
                break;
            case CotizacionesTable::$NIVEL_COTIZACION:
                $resp="Cotizacion";
                break;
            case CotizacionesTable::$NIVEL_TEMPLATE:
                $resp="Template";
                break;
        }
        return $resp;
    }
    
    public function hasNivelCotizacion(){
        if($this->getNivel()==CotizacionesTable::$NIVEL_COTIZACION){
            return true;
        }else{
            return false;
        }
    }
    
    public function hasNivelDetalle(){
        if($this->getNivel()==CotizacionesTable::$NIVEL_DETALLE){
            return true;
        }else{
            return false;
        }
    }
    
}