<?php

/**
 * Eventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Eventos extends BaseEventos
{
    public function __toString() {
        return sprintf("%s con evento",$this->getDetallesCotizacion());
    }
}
