<?php

/**
 * EventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Eventos');
    }
    
  static public $types = array(
    'nunca' => 'Nunca',
    'todos-los-dias' => 'Todos los dias',
    'todas-las-semanas' => 'Todas las semanas',
    'cada-2-semanas' => 'Cada 2 semanas',
    'todos-los-meses' => 'Todos los meses',  
    'todos-los-anos' => 'Todos los años',  
  );
 
  public function getTypes()
  {
    return self::$types;
  }
  
  static public $status = array(
    '0' => 'Sin Evento',
    '1' => 'Apartado',
    '2' => 'Con Evento',
    '3' => 'Vacaciones',
    '4' => 'No disponible',  
  );
 
  public function getTypesStatus()
  {
    return self::$status;
  }
    
}