<?php

/**
 * Facturas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Facturas extends BaseFacturas
{
    function getHayArchivo(){
        $ruta=sfConfig::get('sf_upload_dir').'/facturas/'.$this->getFile();
        return file_exists($ruta);
    }
    
    function save(\Doctrine_Connection $conn = null) {
               
        if(!$this->isNew()){
          $this->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
        }
        
        parent::save($conn);
        
               
    }
    function delete(\Doctrine_Connection $conn = null) {
        if(file_exists(sfConfig::get('sf_uploads_dir').'/facturas/'.$this->getFile())){
           unlink(sfConfig::get('sf_uploads_dir').'/facturas/'.$this->getFile());
           sfContext::getInstance()->getUser()->setFlash('info', "Archivo {$this->getFile()} borrado");
        }
        parent::delete($conn);
    }
    
    function getStringStatus(){
        if($this->getHayArchivo() && $this->getCotizacionId()>0){
            return "Factura asociada";
        }elseif($this->getHayArchivo()){
            return "Factura sin asociar";
        }elseif($this->getCotizacionId()>0){
            return "Cotizacion sin factura";
        }else{
            return "Registro vacio";
        }
    }

    
}
