<?php

/**
 * PagosTalentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PagosTalentos extends BasePagosTalentos
{
    public function calcular(){
        $importe=0;
        $adeudo=0;
        foreach($this->getDetallesPagosTalentos() as $dpt){
            if($dpt->getStatus()==PagosTalentosTable::$PAGOS_CALCULADOS){
                $importe+=$dpt->getImporte();
            }
        }
        $arregloDetallesCotizacion=array();
        foreach($this->getDetallesPagosTalentos() as $dpt){
            $dc=$dpt->getDetallesCotizacion();
             if(count($arregloDetallesCotizacion)>0){
                 if(!in_array($dc->getId(), $arregloDetallesCotizacion)){
                    $adeudo+=$dc->getGananciaTalento();
                    $arregloDetallesCotizacion[]=$dc->getId();
                 }
             }else{
                $adeudo+=$dc->getGananciaTalento();
                $arregloDetallesCotizacion[]=$dc->getId();
             }
        }
        $this->setAdeudo($adeudo-$importe);
        $this->save();
    }
    public function save(\Doctrine_Connection $conn = null) {
        if($this->isNew()){
            $this->setReferencia(date("m-Y"));
        }
        
        parent::save($conn);
    }
}
