<?php

/**
 * Pagos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pagos extends BasePagos
{
    public function calcular(){
        $importe=0;
        $adeudo=0;
        foreach($this->getDetallesPagos() as $dp){
            if($dp->getStatus()==PagosTable::$PAGOS_CALCULADOS){
                $importe+=$dp->getImporte();
            }
        }
        $arregloCotizacion=array();
        foreach($this->getDetallesPagos() as $dp){
            $cot=$dp->getCotizaciones();
             if(count($arregloCotizacion)>0){
                 if(!in_array($cot->getId(), $arregloCotizacion)){
                    $adeudo+=$cot->getSubtotal();
                    $arregloCotizacion[]=$cot->getId();
                 }
             }else{
                $adeudo+=$cot->getSubtotal();
                $arregloCotizacion[]=$cot->getId();
             }
        }
        $this->setAdeudo($adeudo-$importe);
        $this->save();
    }
    public function save(\Doctrine_Connection $conn = null) {
        if($this->isNew()){
            $this->setReferencia(date("m-Y"));
        }
        
        parent::save($conn);
    }
}
