<?php

/**
 * PagosTalentosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PagosTalentosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PagosTalentosTable
     */
    
    static public $INCOMPLETO = 0;      
    static public $APROBADO = 1;      
    static public $PAGOS_CALCULADOS = 2;
    
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PagosTalentos');
    }
    public function getCriteriaOrdenada(){
        $q=Doctrine_Query::create()
           ->from('Pagos p')
           ->orderBy('p.created_at');
        return $q;
    }
    public function getCriteriaOrdenadaPorActualizacion(){
        $q=Doctrine_Query::create()
                ->from('PagosTalentos pt')
                ->orderBy('pt.updated_at DESC');
        return $q;
    }
    public function getCriteriaUltimosPagos(){
        $q=$this->getCriteriaOrdenadaPorActualizacion();
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.Talentos t');
        $q->leftJoin($rootAlias . '.DetallesPagosTalentos dt');
        $q->leftJoin('t.DetallesCotizacion dc');
        return $q;
    }
    
    public function getCriteriaPendientesDePagos(){
        $q=$this->createQuery('pt');  
        $rootAlias = $q->getRootAlias();
        //$user=  sfContext::getInstance()->getUser()->getGuardUser(); 
        //$q->addWhere($rootAlias.'.user_id=?',$user->getId());
        $q->leftJoin($rootAlias . '.Talentos tal');
        $q->leftJoin($rootAlias . '.DetallesPagosTalentos dpt');
        $q->leftJoin('dpt.DetallesCotizacion dc');
        $q->andWhere('dc.is_pay_talento=?',false);
        $user=  sfContext::getInstance()->getUser()->getGuardUser();
        if(!$user->getIsSuperAdmin()){
            //evitar que todos vean todo. solo el super usuario.
            $q->leftJoin('dc.Cotizaciones cot');
            $q->andWhere('cot.user_id=?',$user->getId());    
        }
        return $q;
    }
    public function getPagosPendientesTalentos(){
        $q=$this->getCriteriaPendientesDePagos();
        return $q->execute();
    }
    
    public function getLoteDePagoForTalentoId($id){
      $q=$this->createQuery('pt');  
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Talentos t');
      $q->addWhere($rootAlias.'.talento_id=?',$id);
      $q->addWhere($rootAlias.'.is_cerrado=?',false);
      return $q->fetchOne();
    }
    
    public function retrieveBackendPagosTalentosList(Doctrine_Query $q)
    {
      $user=  sfContext::getInstance()->getUser();   
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Talentos t');
      $q->leftJoin($rootAlias . '.DetallesPagosTalentos dt');
      $q->leftJoin('t.DetallesCotizacion dc');
           
      if(count($user->getTalentos())>0){
            $talentos=$user->getTalentos();
            $q->addWhere('t.id=?', $talentos[0]);
      }
           
      return $q;
    }
    public function getPagosConTalentoDetallesForId($id){
      $q=$this->createQuery('a');  
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Talentos t');
      $q->leftJoin($rootAlias . '.DetallesPagosTalentos dt');
      $q->leftJoin('t.DetallesCotizacion dc');
      $q->addWhere($rootAlias.'.id=?',$id);
      return $q->fetchOne();
    }
    
    public function getPagosConTalentoDetallesForTalentoId($id){
      $q=$this->createQuery('a');  
      $rootAlias = $q->getRootAlias();
      $q->leftJoin($rootAlias . '.Talentos t');
      $q->leftJoin($rootAlias . '.DetallesPagosTalentos dt');
      $q->leftJoin('t.DetallesCotizacion dc');
      $q->addWhere('t.id=?',$id);
      return $q->fetchOne();
    }
    
    public function getPagosTalentosPorArreglo($arreglo){
        $q=$this->getCriteriaOrdenada();
        $rootAlias = $q->getRootAlias();
        $q->andWhereIn($rootAlias.'.id', $arreglo);
        $q->leftJoin($rootAlias . '.Talentos t');
        $q->leftJoin($rootAlias . '.DetallesPagosTalentos dt');
        $q->leftJoin('t.DetallesCotizacion dc');
        return $q->execute();
    }
}