<?php

/**
 * Precotizaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Precotizaciones extends BasePrecotizaciones
{

    public function __toString() {
        return sprintf("%s",$this->getEvento());
    }
    public function getStringStatus(){
        switch($this->getStatus()){
            case 2:
                return "Aprobada";
            case 1:
                return "Enviada a cliente";
            case 0:
                return "En captura";
            case -1:
                return "Cancelado";    
        }
    }
    
    public function statusAprobada(){
        if($this->getStatus()>=PrecotizacionesTable::$APROBADA)
            return true;
        else
            return false;
    }
    
    public function statusEnMediacion(){
        if($this->getStatus()<=PrecotizacionesTable::$MEDIACION)
            return true;
        else
            return false;
    }
    
    public function getRenderMensaje(){
        $cliente = $this->getClientes();
        $evento = $this->getEvento();
        $lugar = $this->getLugarEvento();
        $talentos=$this->getCadenaTalentos();
        
$body = <<<EOD
        <p>
        Estimado Cliente $cliente<br/>
        
        Por medio de la presente le envio la propuesta para el evento: $evento
        el cúal sera realizado en $lugar.<br/>
        
        Los talentos disponibles para este evento son: $talentos; de los cuales se adjunta su precotización<br/>

        Atte. <br/>
        Jerry Ml<br/>
        </p>
EOD;
    return $body;
    
    }
    
    public function getRenderMensaje2(){
        $contacto = $this->getContactos();
        $user= sfContext::getInstance()->getUser()->getGuardUser();
        $usuario=$user->getFirstName()." ".$user->getLastName();
        $email=$user->getEmailAddress();
        $firma=$user->getFirma();
        $direccion= sfContext::getInstance()->getRequest()->getHost();
        
        if(strlen($firma)==0){
           $sFirma="<span style='text-transform:capitalize;'>$usuario</span> Ejecutivo de Cuenta.<br/>Email: $email.<br/>Teléfonos JerryML a especificar.<br/>";
        }else{
           $sFirma="<img src='http://$direccion/uploads/usuarios/$firma'/>"; 
        }
        
$body = <<<EOD
        <p>
        Estimado {$contacto}<br/>

        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        Atentamente:
        <br/>
        $sFirma
        </p>
EOD;

    return $body;
    
    }
    
    public function getCadenaTalentos(){
        $detalles=$this->getDetallesPrecotizacion();
        $talentos=array();
        $cadena="";
        foreach($detalles as $detalle){
            $talentos[]=$detalle->getTalentos()->getName();
        }
        $largo=count($talentos);
        foreach($talentos as $key=>$name){
            $cadena.=$name;
            if($key+1<$largo){
                $cadena.=", ";
            }
        }
        return $cadena;
    }
    
    public function calcular(){
        //no tiene accion.
    }
    public function validarAprobar(){
        $detalles_precotizacion=$this->getDetallesPrecotizacion();
        $cont=0;
        $valido=true;
        foreach ($detalles_precotizacion as $detalle){
            if($detalle->getPrecio()>0){
                $cont++;
                $valido=true;
            }else{
                $valido=false;
                break;
            }
        }
        if($cont>0){
            return $valido;
        }else{
            return false;
        }
    }
    
    public function getErroresAprobar(){
        $detalles_precotizacion=$this->getDetallesPrecotizacion();
        $cont=0;
        $mensaje="";
        foreach ($detalles_precotizacion as $detalle){
            if($detalle->getPrecio()<=0){
                $cont++;
                $mensaje.="El talento: ".$detalle->getTalentos()." sin importe";
            }
        }
        if($cont>0){
            return $mensaje;
        }else{
            return "No hay registros en la precotizacion";
        }
    }
    
    public function save(\Doctrine_Connection $conn = null) {
        
        if(!$this->getEmpresaId()){
            $empresas=  Doctrine_Core::getTable('Empresas')->getEmpresas();
            $this->setEmpresaId($empresas[0]->getId());
        }
                
        if(!$this->getEvento()){
            $this->setEvento("Nueva Precotizacion");
        }
        if(!$this->getIniciaEvento()){
            $this->setIniciaEvento(date("Y-m-d 00:00:00"));
        }
        if(!$this->getTerminaEvento()){
            $this->setTerminaEvento(date("Y-m-d 00:00:00"));
        }
        
        
        parent::save($conn);
    }
    public function delete(\Doctrine_Connection $conn = null) {
        if(!$this->statusAprobada()){
            $detalles_precotizacion=$this->getDetallesPrecotizacion();
            foreach ($detalles_precotizacion as $detalle){
                $detalle->delete();
            }
            parent::delete($conn);
        }else{
            false;
        }
    }
}
