<?php

/**
 * ProyectosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proyectos');
    }
    
}