<?php

/**
 * RepresentantesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RepresentantesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RepresentantesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Representantes');
    }
}