<?php

/**
 * Talentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Talentos extends BaseTalentos
{
    public function __toString(){
        return sprintf("%s", $this->getName());
    }
    public function removeEventos($arrayEventos){
        $eventos=Doctrine_Core::getTable("KsWCEvent")->getEventosPorArreglo($arrayEventos);
        foreach($eventos as $evento){
            $evento->delete();
        }
    }
}
