var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "d L yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Lun",
            "tue": "Mar",
            "wed": "Mie",
            "thu": "Jue",
            "fri": "Vie",
            "sat": "Sab",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implementado todavia",
        "to_date_view": "Clic para ver el dia actual",
        "i_undefined": "Indefinido",
        "allday_event": "Todo el dia",
        "repeat_event": "Repetir evento",
        "time": "Tiempo",
        "event": "Evento",
        "location": "Localidad",
        "participant": "Participante",
        "get_data_exception": "Excepción al obtener datos",
        "new_event": "Nuevo evento",
        "confirm_delete_event": "¿Confirma usted eliminar este evento? ",
        "confrim_delete_event_or_all": "¿Quieres repetir todos los eventos o sólo este evento? \r\nClick [OK] para eliminar solo este evento, click [Cancelar] para eliminar todos los eventos",
        "data_format_error": "Error de datos en formato! ",
        "invalid_title": "Título del evento no puede estar en blanco",
        "view_no_ready": "Vista no está listo",
        "example": "por ejemplo, la reunión en la sala de juntas",
        "content": "Que?",
        "create_event": "Crear evento",
        "update_detail": "Editar detalles",
        "click_to_detail": "Ver detalles",
        "i_delete": "Eliminar",
        "day_plural": "dias",
        "others": "Otros",
        "item": ""
    }
});
