<?php

/**
 * BaseKsWCEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $talento_id
 * @property varchar $subject
 * @property string $description
 * @property timestamp $start_time
 * @property timestamp $end_time
 * @property boolean $is_all_day_event
 * @property varchar $color
 * @property varchar $recurring_rule
 * @property string $lugar_evento
 * @property string $calle
 * @property string $numero_exterior
 * @property string $numero_interior
 * @property string $colonia
 * @property string $codigo_postal
 * @property string $cuidad
 * @property string $municipio
 * @property string $estado
 * @property string $pais
 * @property integer $status
 * @property Talentos $Talentos
 * @property Doctrine_Collection $Cotizaciones
 * @property Doctrine_Collection $CotizacionesEventos
 * 
 * @method integer             getTalentoId()           Returns the current record's "talento_id" value
 * @method varchar             getSubject()             Returns the current record's "subject" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method timestamp           getStartTime()           Returns the current record's "start_time" value
 * @method timestamp           getEndTime()             Returns the current record's "end_time" value
 * @method boolean             getIsAllDayEvent()       Returns the current record's "is_all_day_event" value
 * @method varchar             getColor()               Returns the current record's "color" value
 * @method varchar             getRecurringRule()       Returns the current record's "recurring_rule" value
 * @method string              getLugarEvento()         Returns the current record's "lugar_evento" value
 * @method string              getCalle()               Returns the current record's "calle" value
 * @method string              getNumeroExterior()      Returns the current record's "numero_exterior" value
 * @method string              getNumeroInterior()      Returns the current record's "numero_interior" value
 * @method string              getColonia()             Returns the current record's "colonia" value
 * @method string              getCodigoPostal()        Returns the current record's "codigo_postal" value
 * @method string              getCuidad()              Returns the current record's "cuidad" value
 * @method string              getMunicipio()           Returns the current record's "municipio" value
 * @method string              getEstado()              Returns the current record's "estado" value
 * @method string              getPais()                Returns the current record's "pais" value
 * @method integer             getStatus()              Returns the current record's "status" value
 * @method Talentos            getTalentos()            Returns the current record's "Talentos" value
 * @method Doctrine_Collection getCotizaciones()        Returns the current record's "Cotizaciones" collection
 * @method Doctrine_Collection getCotizacionesEventos() Returns the current record's "CotizacionesEventos" collection
 * @method KsWCEvent           setTalentoId()           Sets the current record's "talento_id" value
 * @method KsWCEvent           setSubject()             Sets the current record's "subject" value
 * @method KsWCEvent           setDescription()         Sets the current record's "description" value
 * @method KsWCEvent           setStartTime()           Sets the current record's "start_time" value
 * @method KsWCEvent           setEndTime()             Sets the current record's "end_time" value
 * @method KsWCEvent           setIsAllDayEvent()       Sets the current record's "is_all_day_event" value
 * @method KsWCEvent           setColor()               Sets the current record's "color" value
 * @method KsWCEvent           setRecurringRule()       Sets the current record's "recurring_rule" value
 * @method KsWCEvent           setLugarEvento()         Sets the current record's "lugar_evento" value
 * @method KsWCEvent           setCalle()               Sets the current record's "calle" value
 * @method KsWCEvent           setNumeroExterior()      Sets the current record's "numero_exterior" value
 * @method KsWCEvent           setNumeroInterior()      Sets the current record's "numero_interior" value
 * @method KsWCEvent           setColonia()             Sets the current record's "colonia" value
 * @method KsWCEvent           setCodigoPostal()        Sets the current record's "codigo_postal" value
 * @method KsWCEvent           setCuidad()              Sets the current record's "cuidad" value
 * @method KsWCEvent           setMunicipio()           Sets the current record's "municipio" value
 * @method KsWCEvent           setEstado()              Sets the current record's "estado" value
 * @method KsWCEvent           setPais()                Sets the current record's "pais" value
 * @method KsWCEvent           setStatus()              Sets the current record's "status" value
 * @method KsWCEvent           setTalentos()            Sets the current record's "Talentos" value
 * @method KsWCEvent           setCotizaciones()        Sets the current record's "Cotizaciones" collection
 * @method KsWCEvent           setCotizacionesEventos() Sets the current record's "CotizacionesEventos" collection
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKsWCEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ks_w_c_event');
        $this->hasColumn('talento_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subject', 'varchar', 64, array(
             'type' => 'varchar',
             'notnull' => false,
             'length' => 64,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('start_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('end_time', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('is_all_day_event', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('color', 'varchar', 10, array(
             'type' => 'varchar',
             'length' => 10,
             ));
        $this->hasColumn('recurring_rule', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('lugar_evento', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('calle', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('numero_exterior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('numero_interior', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('colonia', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('codigo_postal', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('cuidad', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('municipio', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('estado', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('pais', 'string', 150, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 150,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Talentos', array(
             'local' => 'talento_id',
             'foreign' => 'id'));

        $this->hasMany('Cotizaciones', array(
             'refClass' => 'CotizacionesEventos',
             'local' => 'cotizacion_id',
             'foreign' => 'evento_id'));

        $this->hasMany('CotizacionesEventos', array(
             'local' => 'id',
             'foreign' => 'evento_id'));
    }
}