<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/28 22:44:28
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#000000',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'JerryMLAdmin',
  'app_sf_admin_dash_include_path' => false,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_sf_admin_dash_categories' => array (
  'Sistema' => 
  array (
    'items' => 
    array (
      'Usuarios' => 
      array (
        'url' => 'sf_guard_user',
        'image' => 'users.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'usuarios',
            1 => 'admin',
          ),
        ),
      ),
      'Grupos' => 
      array (
        'url' => 'sf_guard_group',
        'image' => 'addusers.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Permisos' => 
      array (
        'url' => 'sf_guard_permission',
        'image' => 'config.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Configuracion' => 
      array (
        'url' => 'configuracion',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Comisionistas' => 
      array (
        'url' => 'comisionistas',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Conceptos' => 
      array (
        'url' => 'conceptos',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
      'Empresas' => 
      array (
        'url' => 'empresas',
        'image' => 'cpanel.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
    ),
  ),
  'Administracion' => 
  array (
    'items' => 
    array (
      'Empresas' => 
      array (
        'url' => 'clientes',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'clientes',
            1 => 'admin',
          ),
        ),
      ),
      'Contactos' => 
      array (
        'url' => 'contactos',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'clientes',
            1 => 'admin',
          ),
        ),
      ),
      'Talentos' => 
      array (
        'url' => 'talentos',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'talentos',
            1 => 'admin',
          ),
        ),
      ),
      'Calendario Talentos' => 
      array (
        'url' => 'calendario_talentos',
        'image' => 'support.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'talentos',
            1 => 'admin',
          ),
        ),
      ),
      'Calendario Usuarios' => 
      array (
        'url' => 'calendario_usuarios',
        'image' => 'support.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'usuarios',
            1 => 'admin',
          ),
        ),
      ),
    ),
  ),
  'Operaciones' => 
  array (
    'items' => 
    array (
      'Pre-cotizaciones' => 
      array (
        'url' => 'precotizaciones',
        'image' => 'mediamanager.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'cotizaciones',
            1 => 'admin',
          ),
        ),
      ),
      'Cotizaciones' => 
      array (
        'url' => 'cotizaciones',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'cotizaciones',
            1 => 'admin',
          ),
        ),
      ),
      'Contratos' => 
      array (
        'url' => 'contratos',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'contratos',
            1 => 'admin',
          ),
        ),
      ),
      'Facturas' => 
      array (
        'url' => 'facturas',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'contratos',
            1 => 'admin',
          ),
        ),
      ),
      'Pagos Clientes' => 
      array (
        'url' => 'pagos',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'pagos_clientes',
            1 => 'admin',
          ),
        ),
      ),
      'Pagos Talentos' => 
      array (
        'url' => 'pagos_talentos',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 
          array (
            0 => 'pagos_talentos',
            1 => 'admin',
          ),
        ),
      ),
      'Reportes' => 
      array (
        'url' => 'reportes',
        'image' => 'module.png',
        'credentials' => 
        array (
          0 => 'admin',
        ),
      ),
    ),
  ),
),
  'app_laigu_feyasoft_calendar_plugin_web_dir_extjs' => '/js/extjs',
  'app_sf_jerryml_admin_iva' => 0.16,
  'app_sf_jerryml_admin_con_iva' => 1.16,
  'app_dbformextraplugin_include_jquery' => false,
  'app_dbformextraplugin_jquery_path' => '/dbFormExtraPlugin/jquery/',
  'app_dbformextraplugin_jquery_version' => 'jquery-1.2.6.min.js',
  'app_dbformextraplugin_jqueryui_path' => '/dbFormExtraPlugin/jquery_ui/js/',
  'app_dbformextraplugin_jqueryui_path_css' => '/dbFormExtraPlugin/jquery_ui/css/',
  'app_dbformextraplugin_datetime_path_js' => '/dbFormExtraPlugin/datetime/js/',
  'app_dbformextraplugin_datetime_path_css' => '/dbFormExtraPlugin/datetime/css/',
));
