<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/28 22:46:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfjerrymladmin4',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
