<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/04 21:15:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfjerrymladmin5',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
