<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/28 22:47:01
sfConfig::add(array(
  'mod_detcotizaciones_enabled' => true,
  'mod_detcotizaciones_view_class' => 'sfPHP',
));
