<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/04 21:15:23
sfConfig::add(array(
  'mod_eventos_usuarios_enabled' => true,
  'mod_eventos_usuarios_view_class' => 'sfPHP',
));
