generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Pagos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          pagos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        clientes:   { label: Empresa }
        referencia: { label: Referencia }
        is_cerrado: { label: Cerrado }
        pagos_by_cliente: {label: Empresa, help: Nombre Empresa o RFC }
        pagos_by_referencia: {label: Referencia, help: Referencia del pago }
        importe: {label: Importe }
        iva: {label: IVA}
      list:    
        title: Pagos
        table_method: retrieveBackendPagosList
        sort: [created_at, asc]
        display: [id, referencia, clientes, _importe, _iva, _saldo, is_cerrado]
        batch_actions: {}
        object_actions:
          show:     { label: Mostrar, action: show  }
          close:    { label: Cerrar Lote, action: close }
        actions: {}
        #  crear:    { label: Nuevo Pago, action: crearPago  }
      filter:  
        display: [pagos_by_cliente, pagos_by_referencia]
      form: 
        actions:
          _list: {label: Regresar a Lista}
          _save: {label: Guardar }
      edit: 
        title: Editar pago %%referencia%%
        display:
          Cliente:     [_cliente]
          Referencia:  [referencia]
      new:
        title: Crear Pago
        display:
          Cliente:     [_cliente]
          Referencia:  [referencia]
          