<?php

/**
 * EventosUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EventosUsuarios extends PluginEventosUsuarios
{
    public function save(\Doctrine_Connection $conn = null) {
        
        $this->setIsAllDayEvent(sfRichSys::getFechasTodoElDia($this->getStartTime(), $this->getEndTime()));
        
        
        parent::save($conn);
    }
    
    public function crearEventoDesdeCotizacion(Cotizaciones $cot){
        $this->setCotizacionId($cot->getId());
        $this->setUserId($cot->getManagerId());
        $this->setSubject($cot->getDescripcion());
        $this->setDescription($cot->getActividad());
        $this->setStartTime($cot->getFechaDesde());
        $this->setEndTime($cot->getFechaHasta());
        $this->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
        $this->save();
    }
    public function actualizarEventoDesdeCotizacion(Cotizaciones $cot){
        $this->setUserId($cot->getManagerId());
        $this->setSubject($cot->getDescripcion());
        $this->setDescription($cot->getActividad());
        $this->setStartTime($cot->getFechaDesde());
        $this->setEndTime($cot->getFechaHasta());
        $this->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
        $this->save();
    }
}
