<?php

/**
 * KsWCEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KsWCEvent extends PluginKsWCEvent
{
    public function save(\Doctrine_Connection $conn = null) {
        
        $this->setIsAllDayEvent(sfRichSys::getFechasTodoElDia($this->getStartTime(), $this->getEndTime()));
        
        
        parent::save($conn);
    }
    public function __toString() {
        return sprintf("%s | %s | ", 
                $this->getSubject(),
                sfRichSys::getStringFechasInicialFinal($this->getStartTime(), $this->getEndTime()));
    }
    public function getColor(){
        switch($this->getStatus()){
            case KsWCEventTable::$DISPONIBLE:
                //$color="#800080"; morado
                $color="3";
                break;
            case KsWCEventTable::$PERSONAL:
                //$color="#800080"; gris
                $color="5";
                break;
            case KsWCEventTable::$EN_MEDIACION:
                //$color="#0000A0"; azul
                $color="6";
                break;
            case KsWCEventTable::$APARTADO:
                //$color="#00FF00"; verde
                $color="7";
                break;
        }
        return $color;
    }
    public function getStatusString(){
        switch($this->getStatus()){
            case KsWCEventTable::$DISPONIBLE:
                $resp="Disponible";
                break;
            case KsWCEventTable::$PERSONAL:
                $resp="Personal";
                break;
            case KsWCEventTable::$EN_MEDIACION:
                $resp="En mediacion";
                break;
            case KsWCEventTable::$APARTADO:
                $resp="Apartado";
                break;
        }
        return $resp;
    }
    
    public function mediacionEvento(){
        $this->setStatus(KsWCEventTable::$EN_MEDIACION);
        $this->save();
    }
    
    public function apartarEvento(){
        $this->setStatus(KsWCEventTable::$APARTADO);
        $this->save();
    }
    
    public function statusApartado(){
        return ($this->getStatus()>KsWCEventTable::$EN_MEDIACION?true:false);
    }
    
    public function getNivelString(){
        $resp="";
        switch($this->getNivel()){
            case CotizacionesTable::$NIVEL_DETALLE:
               $resp="Detalle";
                break;
            case CotizacionesTable::$NIVEL_COTIZACION:
                $resp="Cotizacion";
                break;
            case CotizacionesTable::$NIVEL_TEMPLATE:
                $resp="Template";
                break;
        }
        return $resp;
    }
    
    public function hasNivelCotizacion(){
        if($this->getNivel()==CotizacionesTable::$NIVEL_COTIZACION){
            return true;
        }else{
            return false;
        }
    }
    
    public function hasNivelDetalle(){
        if($this->getNivel()==CotizacionesTable::$NIVEL_DETALLE){
            return true;
        }else{
            return false;
        }
    }
    
    public function crearEventoDesdeCotizacion(Cotizaciones $cot,DetallesCotizacion $dc){
        $this->setDetallesCotizacionId($dc->getId());
        $this->setTalentoId($dc->getTalentoId());
        $this->setSubject($cot->getDescripcion());
        $this->setDescription($cot->getActividad());
        $this->setStartTime($cot->getFechaDesde());
        $this->setEndTime($cot->getFechaHasta());
        $this->setLugarEvento($cot->getPlaza());
        $this->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
        $this->save();
    }
    public function actualizarEventoDesdeCotizacion(Cotizaciones $cot){
        $this->setSubject($cot->getDescripcion());
        $this->setDescription($cot->getActividad());
        $this->setStartTime($cot->getFechaDesde());
        $this->setEndTime($cot->getFechaHasta());
        $this->setLugarEvento($cot->getPlaza());
        $this->setNivel(CotizacionesTable::$NIVEL_COTIZACION);
        $this->save();
    }
    
    public function getDescriptionLimpia(){
        if($this->getDescription()){
            $texto= str_replace("<p>","",$this->getDescription());
            return str_replace("</p>", "", $texto);
        }else{
            return "";
        }
    }
    
}
