<?php

/**
 * KsWCEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfJerryMlAdmin
 * @subpackage model
 * @author     Ricardo Alcantara Gomez <richpolis@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class KsWCEvent extends PluginKsWCEvent
{
    public function __toString() {
        return sprintf("%s | %s | %s", 
                $this->getSubject(),
                sfRichSys::getStringFechasInicialFinal($this->getStartTime(), $this->getEndTime()),
                $this->getDescription());
    }
    public function getColor(){
        switch($this->getStatus()){
            case KsWCEventTable::$DISPONIBLE:
                //$color="#800080"; morado
                $color="3";
                break;
            case KsWCEventTable::$PERSONAL:
                //$color="#800080"; gris
                $color="5";
                break;
            case KsWCEventTable::$EN_MEDIACION:
                //$color="#0000A0"; azul
                $color="6";
                break;
            case KsWCEventTable::$APARTADO:
                //$color="#00FF00"; verde
                $color="7";
                break;
        }
        return $color;
    }
    public function getStatusString(){
        switch($this->getStatus()){
            case KsWCEventTable::$DISPONIBLE:
                $resp="Disponible";
                break;
            case KsWCEventTable::$PERSONAL:
                $resp="Personal";
                break;
            case KsWCEventTable::$EN_MEDIACION:
                $resp="En mediacion";
                break;
            case KsWCEventTable::$APARTADO:
                $resp="Apartado";
                break;
        }
        return $resp;
    }
    
    public function mediacionEvento(){
        $this->setStatus(KsWCEventTable::$EN_MEDIACION);
        $this->save();
    }
    
    public function apartarEvento(){
        $this->setStatus(KsWCEventTable::$APARTADO);
        $this->save();
    }
    
    public function statusApartado(){
        return ($this->getStatus()>KsWCEventTable::$EN_MEDIACION?true:false);
    }
    
}
