<?php

/**
 * UsuariosEventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuariosEventosTable extends PluginUsuariosEventosTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuariosEventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuariosEventos');
    }
}