<?php

/**
 * PluginEventosUsuariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventosUsuariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventosUsuariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventosUsuarios');
    }
}