<?php

/**
 * PluginUsuariosEventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUsuariosEventosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUsuariosEventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUsuariosEventos');
    }
}